server:
  port: 8080
spring:
  application:
    name: auth.service
  datasource:
    url: jdbc:postgresql://postgresdb:5432/auth_service
    username: postgres
    password: 1234
  data:
    redis:
      database: 1
      host: redis
      port: 6379
      password: 1234
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
      group-id: auth.service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
app:
  sign-up:
    admin:
      password: 1234

